# Generated by Django 4.2.21 on 2025-07-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=35, max_digits=40, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=35, max_digits=40, null=True)),
                ('start_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10)),
                ('end_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Friday', max_length=10)),
                ('start_time', models.TimeField(default='07:00')),
                ('end_time', models.TimeField(default='19:00')),
                ('is_active', models.BooleanField(default=False)),
                ('distance', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
            ],
        ),
    ]
