# Generated by Django 4.2.21 on 2025-07-09 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentsms',
            options={'ordering': ['-sent_date']},
        ),
        migrations.AddField(
            model_name='sentsms',
            name='recipient_type',
            field=models.CharField(choices=[('guardian', 'Guardian'), ('staff', 'Staff'), ('other', 'Other')], default='guardian', max_length=10),
        ),
        migrations.AlterField(
            model_name='sentsms',
            name='dest_addr',
            field=models.CharField(db_index=True, max_length=13, verbose_name='Destination (+255…)'),
        ),
        migrations.AlterField(
            model_name='sentsms',
            name='first_name',
            field=models.CharField(blank=True, default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentsms',
            name='last_name',
            field=models.CharField(blank=True, default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentsms',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sentsms',
            name='network',
            field=models.CharField(blank=True, default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentsms',
            name='sent_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sentsms',
            name='sms_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sentsms',
            name='status',
            field=models.CharField(db_index=True, default='Sent', max_length=16),
        ),
        migrations.AddIndex(
            model_name='sentsms',
            index=models.Index(fields=['dest_addr'], name='sms_sentsms_dest_ad_1c8782_idx'),
        ),
        migrations.AddIndex(
            model_name='sentsms',
            index=models.Index(fields=['sent_date'], name='sms_sentsms_sent_da_ca4619_idx'),
        ),
    ]
