# Generated by Django 4.2.21 on 2025-07-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_sentsms_options_sentsms_recipient_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentsms',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sentsms',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sentsms',
            name='network',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sentsms',
            name='source_addr',
            field=models.CharField(default='VICTORY-PPS', max_length=50),
        ),
    ]
