# Generated by Django 4.2.21 on 2025-07-04 22:44

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('firstname', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('date_of_admission', models.DateField(default=django.utils.timezone.now)),
                ('staff_category', models.CharField(choices=[('teaching', 'Teaching'), ('non_teaching', 'Non‑Teaching')], default='teaching', max_length=20)),
                ('job_title', models.CharField(blank=True, help_text='Free‑text vacancy / title (e.g. ‘Math Teacher’ or ‘Bursar’)', max_length=120)),
                ('department', models.CharField(choices=[('teaching', 'Teaching'), ('administration', 'Administration'), ('maintenance', 'Maintenance'), ('catering', 'Catering'), ('security', 'Security')], default='teaching', max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('special_allowance', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Optional additional allowance (e.g. Head‑master duty) paid on top of basic salary.', max_digits=10)),
                ('has_helsb', models.BooleanField(default=False, help_text='Tick if this employee has an active HELSB loan deduction.')),
                ('helsb_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='HELSB deduction **percent**. Example\xa015.00 ⇒\xa015\xa0%', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('mobile_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Mobile number must be in the format\xa0+255XXXXXXXXX', regex='^\\+255[0-9]{9}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Mobile number must be in the format\xa0+255XXXXXXXXX', regex='^\\+255[0-9]{9}$')])),
                ('guarantor', models.CharField(blank=True, max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nida_id', models.CharField(blank=True, max_length=20, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contract_duration', models.CharField(blank=True, max_length=50)),
                ('contract_start_date', models.DateField(default=django.utils.timezone.now)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Bank account number must be 10‑20 digits', regex='^[0-9]{10,20}$')])),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_photo', models.ImageField(blank=True, upload_to='staffs/passports/')),
                ('others', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['surname', 'firstname'],
                'permissions': [('view_staff_list', 'Can view staff list'), ('view_staff_detail', 'Can view staff details')],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_present', models.BooleanField(default=False)),
                ('time_of_arrival', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'user'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
