# Generated by Django 4.2.21 on 2025-07-04 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('ANNUAL', 'Annual'), ('MONTH', 'Monthly'), ('TERM', 'Per Term'), ('SEASON', 'Seasonal')], default='TERM', max_length=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='corecode.installment'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='corecode.academicterm'),
        ),
    ]
