# Generated by Django 4.2.21 on 2025-07-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_budget_category_alter_budget_installment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='installment',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='term',
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('ANNUAL', 'Annual'), ('MONTHLY', 'Monthly'), ('SEASONAL', 'Seasonal')], default='ANNUAL', max_length=10),
        ),
    ]
