# Generated by Django 4.2.21 on 2025-07-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_budget_installment_remove_budget_term_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deduction',
            name='deduction_amount_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='salaryinvoice',
            name='basic_salary_positive',
        ),
        migrations.RemoveConstraint(
            model_name='salaryinvoice',
            name='unique_salary_per_month',
        ),
        migrations.RemoveConstraint(
            model_name='salaryinvoice',
            name='paye_non_negative',
        ),
        migrations.AddConstraint(
            model_name='deduction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='deduction_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='salaryinvoice',
            constraint=models.CheckConstraint(check=models.Q(('basic_salary__gt', 0)), name='payslip_basic_positive'),
        ),
        migrations.AddConstraint(
            model_name='salaryinvoice',
            constraint=models.CheckConstraint(check=models.Q(('paye_amount__gte', 0)), name='payslip_paye_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='salaryinvoice',
            constraint=models.UniqueConstraint(fields=('staff', 'month'), name='unique_staff_month'),
        ),
    ]
