# Generated by Django 4.2.21 on 2025-07-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_deduction_deduction_amount_non_negative_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deduction',
            name='deduction_nonneg',
        ),
        migrations.AddConstraint(
            model_name='deduction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='deduction_non_negative'),
        ),
    ]
