# Generated by Django 4.2.21 on 2025-07-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_deduction_deduction_nonneg_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salaryinvoice',
            name='unique_staff_month',
        ),
        migrations.AddConstraint(
            model_name='salaryinvoice',
            constraint=models.UniqueConstraint(fields=('staff', 'month'), name='uniq_staff_calmonth'),
        ),
    ]
