# Generated by Django 4.2.21 on 2025-07-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_salaryinvoice_unique_staff_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deduction',
            options={'ordering': ['salary_invoice_id', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='deduction',
            name='deduction_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='salaryinvoice',
            name='payslip_basic_positive',
        ),
        migrations.RemoveConstraint(
            model_name='salaryinvoice',
            name='payslip_paye_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='salaryinvoice',
            name='uniq_staff_calmonth',
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('ANNUAL', 'Annual'), ('MONTHLY', 'Monthly'), ('TERM', 'Per Term'), ('SEASONAL', 'Seasonal')], default='ANNUAL', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='deduction',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='deduction_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='salaryinvoice',
            constraint=models.CheckConstraint(check=models.Q(('basic_salary__gt', 0)), name='slip_basic_positive'),
        ),
        migrations.AddConstraint(
            model_name='salaryinvoice',
            constraint=models.CheckConstraint(check=models.Q(('paye_amount__gte', 0)), name='slip_paye_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='salaryinvoice',
            constraint=models.UniqueConstraint(fields=('staff', 'month'), name='uniq_staff_calendar_month'),
        ),
    ]
