# Generated by Django 4.2.21 on 2025-07-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_deduction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfees',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
