# Generated by Django 4.2.21 on 2025-07-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_schoolfees_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfees',
            name='annual_amount',
            field=models.IntegerField(),
        ),
    ]
