# Generated by Django 4.2.21 on 2025-07-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_schoolfees_annual_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='balance_from_previous_install',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_amount',
            field=models.IntegerField(default=0),
        ),
    ]
