# Generated by Django 4.2.21 on 2025-07-08 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian2_mobile_number',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Registration number must be in the format SXXXXXXX/XXXX/YYYY (e.g., S1234567/0032/2025).', regex='^S[0-9]{7}/[0-9]{4}/[0-9]{4}$')]),
        ),
    ]
