# Generated by Django 4.2.21 on 2025-07-07 23:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyconsumption',
            name='quantity_used',
            field=models.DecimalField(decimal_places=2, help_text='How much of the processed item was eaten / used.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='processingbatch',
            name='input_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Kg (raw) fed into the mill / press', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='processingbatch',
            name='output_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Kg/L produced', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='processingbatch',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='TZS spent on milling / pressing', max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
