# Generated by Django 4.2.21 on 2025-07-07 23:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_deduction_options_and_more'),
        ('expenditures', '0002_alter_dailyconsumption_quantity_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='amount',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price @ unit (TZS)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenditure',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_expenditures', to='finance.budget'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='budget_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenditures', to='expenditures.budgetline'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenditures', to='finance.receipt'),
        ),
        migrations.AddIndex(
            model_name='expenditure',
            index=models.Index(fields=['total_cost'], name='expenditure_total_c_e34df9_idx'),
        ),
    ]
