# Generated by Django 4.2.21 on 2025-07-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditures', '0003_remove_expenditure_amount_expenditure_price_per_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonalproduct',
            name='created',
        ),
        migrations.RemoveField(
            model_name='seasonalproduct',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='seasonalpurchase',
            name='created',
        ),
        migrations.RemoveField(
            model_name='seasonalpurchase',
            name='modified',
        ),
        migrations.AddField(
            model_name='seasonalpurchase',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
    ]
