# Generated by Django 4.2.21 on 2025-07-04 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('staffs', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='staff',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='secretaryuser',
            name='staff',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='student',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='bursoruser',
            name='staff',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='academicuser',
            name='staff',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='staffs.staff'),
        ),
    ]
