# Generated by Django 4.2.21 on 2025-07-09 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadTeacherUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('staff', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='staffs.staff')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.customuser',),
        ),
    ]
