from django.urls import path
from . import views


urlpatterns = [
    # budgets
    path("budgets/dashboard/", views.BudgetDashboardView.as_view(),  name="budget-dashboard"),
    path("budgets/",               views.BudgetListView.as_view(),   name="budget-list"),
    path("budgets/create/",        views.BudgetCreateView.as_view(), name="budget-create"),
    path("budgets/<int:pk>/edit/", views.BudgetUpdateView.as_view(), name="budget-update"),
    path("budgets/<int:pk>/delete/", views.BudgetDeleteView.as_view(), name="budget-delete"),

 path("receipts/create/student/<int:student_id>/",views.StudentReceiptCreateView.as_view(),name="student-receipt-create"),

    path("api/staff/<int:pk>/defaults/", views.staff_defaults, name="staff-defaults"),
    path("invoices/", views.InvoiceListView.as_view(), name="invoice-list"),
    path("invoices/create/", views.InvoiceCreateView.as_view(), name="invoice-create"),
    path("invoices/<int:pk>/detail/", views.InvoiceDetailView.as_view(), name="invoice-detail"),
    path("invoices/<int:pk>/update/", views.InvoiceUpdateView.as_view(), name="invoice-update"),
    path("invoices/<int:pk>/delete/", views.InvoiceDeleteView.as_view(), name="invoice-delete"),
    path("receipts/create/", views.ReceiptCreateView.as_view(), name="receipt-create"),
    path("receipts/<int:pk>/update/", views.ReceiptUpdateView.as_view(), name="receipt-update"),
    path("receipts/<int:pk>/delete/", views.ReceiptDeleteView.as_view(), name="receipt-delete"),
    path("school-fees/", views.SchoolFeesListView.as_view(), name="school-fees-list"),
    path("school-fees/create/", views.SchoolFeesCreateView.as_view(), name="school-fees-create"),
    path("school-fees/<int:pk>/update/", views.SchoolFeesUpdateView.as_view(), name="school-fees-update"),
    path("school-fees/<int:pk>/delete/", views.SchoolFeesDeleteView.as_view(), name="school-fees-delete"),
    path("salaries/", views.SalaryInvoiceListView.as_view(), name="salary-invoice-list"),
    path("salaries/create/", views.SalaryInvoiceCreateView.as_view(), name="salary-invoice-create"),
    path("salaries/<int:pk>/detail/", views.SalaryInvoiceDetailView.as_view(), name="salary-invoice-detail"),
    path("salaries/<int:pk>/update/", views.SalaryInvoiceUpdateView.as_view(), name="salary-invoice-update"),
    path("salaries/<int:pk>/delete/", views.SalaryInvoiceDeleteView.as_view(), name="salary-invoice-delete"),
    path("uniforms/", views.uniform_list, name="uniform_list"),
    path("uniforms/create/", views.uniform_create, name="uniform-create"),
    path("uniforms/<int:student_id>/detail/", views.uniform_detail, name="uniform-detail"),
    path("uniforms/<int:pk>/update/", views.uniform_update, name="uniform-update"),
    path("uniforms/<int:pk>/delete/", views.uniform_delete, name="uniform-delete"),
    path("student-uniforms/", views.student_uniform_list, name="student-uniform-list"),
    path("student-uniforms/<int:student_id>/create/", views.student_uniform_create, name="student-uniform-create"),
    path("student-uniforms/<int:pk>/update/", views.student_uniform_update, name="student-uniform-update"),
    path("student-uniforms/<int:pk>/delete/", views.student_uniform_delete, name="student-uniform-delete"),
    path("uniform-types/", views.UniformTypeListView.as_view(), name="uniformtype_list"),
    path("uniform-types/create/", views.UniformTypeCreateView.as_view(), name="uniformtype-create"),
    path("uniform-types/<int:pk>/update/", views.UniformTypeUpdateView.as_view(), name="uniformtype-update"),
    path("uniform-types/<int:pk>/delete/", views.UniformTypeDeleteView.as_view(), name="uniformtype-delete"),
    path("students/search/", views.student_search, name="student-search"),
    path("students/class/", views.get_student_class, name="get-student-class"),
    path("students/balance/", views.get_student_balance, name="get-student-balance"),
    path("school-fees/get/", views.get_school_fees, name="get-school-fees"),
    path("remaining-balance/", views.get_remaining_balance, name="get-remaining-balance"),
    path("uniform-price/", views.get_uniform_price, name="get-uniform-price"),
    path("", views.SelectLinkView.as_view(), name="select_link"),
    path("students/<int:student_id>/info/", views.student_info_api, name="student-info-api"),
    path("salaries/print/", views.print_pdf, name="print-pdf"),
    path("salaries/save/", views.save_pdf, name="save-pdf"),
    path("invoices/<int:pk>/view/",     views.invoice_view,     name="invoice-print"),
    path("invoices/<int:pk>/generate/", views.generate_invoice, name="invoice-generate"),
    path("receipts/<int:receipt_id>/view/",  views.receipt_view,     name="receipt-view"),
    path("receipts/<int:pk>/generate/",      views.generate_receipt, name="generate-receipt"),
    path("salaries/print/", views.print_pdf, name="print_pdf"),
]