# Generated by Django 4.2.21 on 2025-07-04 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('participants', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='corecode.academicsession')),
                ('term', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='corecode.academicterm')),
            ],
        ),
    ]
