# Generated by Django 4.2.21 on 2025-07-04 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('finance', '0001_initial'),
        ('accounts', '0002_initial'),
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('audio_comment', models.FileField(blank=True, null=True, upload_to='student_audio_comments/')),
                ('date_commented', models.DateTimeField(auto_now_add=True)),
                ('date_updated_comments', models.DateTimeField(auto_now=True)),
                ('mark_student_comment', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parentuser')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='ParentComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('audio_comment', models.FileField(blank=True, null=True, upload_to='parent_audio_comments/')),
                ('date_commented', models.DateTimeField(auto_now_add=True)),
                ('date_updated_comments', models.DateTimeField(auto_now=True)),
                ('mark_comment', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='corecode.examtype')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parentuser')),
                ('session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='corecode.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('term', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='corecode.academicterm')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('audio_comment', models.FileField(blank=True, null=True, upload_to='invoice_audio_comments/')),
                ('date_commented', models.DateTimeField(auto_now_add=True)),
                ('date_updated_comments', models.DateTimeField(auto_now=True)),
                ('satisfied', models.BooleanField(default=False)),
                ('installment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='corecode.installment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.invoice')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parentuser')),
                ('session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='corecode.academicsession')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
