# Generated by Django 4.2.21 on 2025-10-03 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text="Short identifier used in URLs (e.g., 'new-campus-2025').", unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project album',
                'verbose_name_plural': 'Project albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'ordering': ['key'], 'verbose_name': 'Site configuration', 'verbose_name_plural': 'Site configurations'},
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='key',
            field=models.SlugField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(help_text='Choose an album to group related photos.', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='corecode.projectalbum')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project photo',
                'verbose_name_plural': 'Project photos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='corecode_pr_created_e0c752_idx')],
            },
        ),
    ]
