# Generated by Django 4.2.21 on 2025-07-04 22:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALevelStudentBulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='alevel_students/bulkupload/')),
            ],
        ),
        migrations.CreateModel(
            name='ALevelStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('registration_number', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Registration number must contain only letters, numbers, slashes, or hyphens (e.g., S0196/001/2025, S133-212-2025).', regex='^[A-Za-z0-9/-]+$')])),
                ('firstname', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('date_of_admission', models.DateField(default=django.utils.timezone.now)),
                ('father_mobile_number', models.CharField(blank=True, default='+255', max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in the right format!", regex='^\\+255[0-9]{9}$')])),
                ('mother_mobile_number', models.CharField(blank=True, max_length=13)),
                ('address', models.TextField(blank=True)),
                ('others', models.TextField(blank=True)),
                ('passport', models.ImageField(blank=True, upload_to='alevel_students/passports/')),
                ('parent_student_id', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.studentclass')),
            ],
            options={
                'ordering': ['firstname', 'middle_name', 'surname'],
            },
        ),
    ]
