# Generated by Django 4.2.21 on 2025-07-04 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('corecode', '0001_initial'),
        ('students', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BursorAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('audio_answer', models.FileField(blank=True, null=True, upload_to='bursor_audio_answers/')),
                ('date_commented', models.DateTimeField(auto_now_add=True)),
                ('date_updated_comments', models.DateTimeField(auto_now=True)),
                ('satisfied', models.BooleanField(default=False)),
                ('installment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='corecode.installment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.invoice')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parentuser')),
                ('session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='corecode.academicsession')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
