from django.urls import path
from .views import (
    secretary_dashboard, secretary_profile, secretary_logout, secretary_details, secretary_salary_invoices, secretary_class_list, secretary_class_results, secretary_all_class_list, secretary_all_class_results, SecretaryEventListView, SecretaryEventDetailView, SecretaryEventCreateView, SecretaryEventUpdateView, SecretaryEventDeleteView, 
    SecretaryDownloadCSVViewdownloadcsv,
    SecretaryStudentBulkUploadView,
    SecretaryStudentCreateView,
    SecretaryStudentDeleteView,
    SecretaryStudentDetailView,
    SecretaryStudentListView,
    SecretaryStudentUpdateView,
    SecretaryInactiveStudentsView,
    SecretarySelectAlluiClassView,
    SecretaryCompletedStudentsView,
    SecretaryCompletedStudentDetailView,
    SecretaryStaffListView,
    SecretarySendSMSFormView, SecretaryCheckBalanceView,
    SecretarySMSHistoryView,
    SecretaryDeleteSMSView,
    StudentCommentsListView,
    SecretaryAddStationeryView,
    SecretaryStationeryListView,
    SecretaryStationeryDetailView,
    SecretaryStationeryUpdateView,
    SecretaryStationeryDeleteView,
    secretary_parent_user_list,
    secretary_create_parent_user,
    secretary_update_parent_user,
    secretary_delete_parent_user,
    mark_comment_as_read,
    mark_secretary_attendance
)

from . import views

urlpatterns = [
    path('secretary/dashboard/', secretary_dashboard, name='secretary_dashboard'),
    path('secretary/profile/', secretary_profile, name='secretary_profile'),
    path('secretary/logout/', secretary_logout, name='secretary_logout'),
    path('secretary/details/', secretary_details, name='secretary_details'),
    path('secretary/salary/invoices/', secretary_salary_invoices, name='secretary_salary_invoices'),
    path('secretary/classes/', secretary_class_list, name='secretary_class_list'),
    path('secretary/classes/<int:class_id>/results/', secretary_class_results, name='secretary_class_results'),
    path('secretary/all/classes/', secretary_all_class_list, name='secretary_all_class_list'),
    path('secretary/all/classes/<int:class_id>/results/', secretary_all_class_results, name='secretary_all_class_results'),
    path('secretary/event/list/', SecretaryEventListView.as_view(), name='secretary_event_list'),
    path('secretary/<int:pk>/', SecretaryEventDetailView.as_view(), name='secretary_event_detail'),
    path('secretary/create/', SecretaryEventCreateView.as_view(), name='secretary_event_create'),
    path('secretary/<int:pk>/update/', SecretaryEventUpdateView.as_view(), name='secretary_event_update'),
    path('secretary/<int:pk>/delete/', SecretaryEventDeleteView.as_view(), name='secretary_event_delete'),
    path("secretary/student/list", SecretaryStudentListView.as_view(), name="secretary-student-list"),
    path("secretary/<int:pk>/student/detail/", SecretaryStudentDetailView.as_view(), name="secretary-student-detail"),
    path("secretary/student/create/", SecretaryStudentCreateView.as_view(), name="secretary-student-create"),
    path("secretary/<int:pk>/update/", SecretaryStudentUpdateView.as_view(), name="secretary-student-update"),
    path("secretary/delete/<int:pk>/", SecretaryStudentDeleteView.as_view(), name="secretary-student-delete"),
    path("secretary/upload/", SecretaryStudentBulkUploadView.as_view(), name="secretary-student-upload"),
    path("secretary-download-csv/", SecretaryDownloadCSVViewdownloadcsv.as_view(), name="secretary-download-csv"),
    path('secretary/students/<int:pk>/delete/', SecretaryStudentDeleteView.as_view(), name='secretary-student-delete'),
    path('secretary-inactive-students/', SecretaryInactiveStudentsView.as_view(), name='secretary-inactive-student-list'),
    path('secretary-select-allui-class/', SecretarySelectAlluiClassView.as_view(), name='secretary-select-allui-class'),
    path('secretary-completed-students/', SecretaryCompletedStudentsView.as_view(), name='secretary-completed-students'),
    path('secretary-completed-student/<int:pk>/', SecretaryCompletedStudentDetailView.as_view(), name='secretary-completed-student-detail'),
    path("secretary/staff/list/", SecretaryStaffListView.as_view(), name="secretary-staff-list"),
    path('secretary-send-sms-form/', SecretarySendSMSFormView.as_view(), name='secretary_send_sms_form'),
    path('secretary-check-balance/', SecretaryCheckBalanceView.as_view(), name='secretary_check_balance'),
    path('secretary-sms-history/', SecretarySMSHistoryView.as_view(), name='secretary_sms_history'),
    path('secretary-delete-sms/', SecretaryDeleteSMSView.as_view(), name='secretary_delete_sms'),
    path('secretary/properties/', views.secretary_property_list, name='secretary_property_list'),
    path('secretary/properties/<int:pk>/', views.secretary_property_detail, name='secretary_property_detail'),
    path('secretary-add-property/', views.secretary_add_property, name='secretary_add_property'),
    path('secretary/properties/<int:pk>/update/', views.secretary_update_property, name='secretary_update_property'),
    path('secretary/properties/<int:pk>/delete/', views.secretary_delete_property, name='secretary_delete_property'),
    path('secretary/student-comments/', StudentCommentsListView.as_view(), name='student_comments'),
    path('secretary_stationery_list/', SecretaryStationeryListView.as_view(), name='secretary_stationery_list'),
    path('secretary_stationery_detail/<int:stationery_id>/', SecretaryStationeryDetailView.as_view(), name='secretary_stationery_detail'),
    path('secretary_stationery_update/<int:stationery_id>/', SecretaryStationeryUpdateView.as_view(), name='secretary_stationery_update'),
    path('secretary_stationery_delete/<int:stationery_id>/', SecretaryStationeryDeleteView.as_view(), name='secretary_stationery_delete'),
    path('secretary_add_stationery/', SecretaryAddStationeryView.as_view(), name='secretary_add_stationery'),
    path('secretary_create_parent_user/', secretary_create_parent_user, name='secretary_create_parent_user'),
    path('secretary_update_parent_user/<int:pk>/', secretary_update_parent_user, name='secretary_update_parent_user'),
    path('secretary_list_parent_users/', secretary_parent_user_list, name='secretary_parent_user_list'),
    path('secretary_delete_parent_user/<int:pk>/', secretary_delete_parent_user, name='secretary_delete_parent_user'),
    path('save-secretary-answer/', views.save_secretary_answer, name='save_secretary_answer'),
    path('mark-comment-as-read/<int:comment_id>/', mark_comment_as_read, name='mark_comment_as_read'),
    path('dashboard/secretary/mark-attendance/', mark_secretary_attendance, name='mark_secretary_attendance'),
]
